name: Build

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Build
        run: mvn -V -B -D"python.executable=${{ steps.setup_python.outputs.python-path }}" package
