name: Build

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macos-latest FFI in native-iamge is not yet supported on aarch64
          - macos-15-intel # x86_64
          - macos-15 # aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Build
        run: mvn -V -B -D"python.executable=${{ steps.setup_python.outputs.python-path }}" package
